table 'Retailer Image'
	lineageTag: 617814d0-4d87-4a60-860d-4d6612d0b779

	measure 'Eucerin sun' = CALCULATE(SUM(FactTable[Value]),FactTable[Product]="Eucerin Sun")
		lineageTag: b78ff894-7a2a-45c6-92c9-4da776c7c933

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Coppertone = CALCULATE(SUM(FactTable[Value]),FactTable[Product]="Coppertone")
		lineageTag: 1ead437d-9c6d-41d6-b41e-625f80408897

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank retailer (Eucerin Sun)' =
			
			If(NOT(ISBLANK([TTL weekly Sales TY (EUCERIN SUN)])), calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),'Key Measures'[TTL weekly Sales TY (EUCERIN SUN)]))
			/* calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),[Total sales(Eucerin SUN)],,desc,skip),'FactTable'[Product]="EUCERIN SUN") */)
		formatString: 0
		lineageTag: d7f43909-25d3-491c-b0f6-464a0270c74b

	measure 'Rank retailer (Coppertone)' =
			
			If(NOT(ISBLANK([TTL weekly Sales TY ( Coppertone)])), calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),'Key Measures'[TTL weekly Sales TY ( Coppertone)])))
			//calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),[TTL MTD Sales TY ( Coppertone)]))
			/* calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),[Total sales(coppertone)]),'FactTable'[Product]="COPPERTONE") */
		formatString: 0
		lineageTag: b0d823f3-b4e2-4675-a4fb-1773311f584a

	measure 'rank x' = CALCULATE( RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),[Total sales]))
		formatString: 0
		lineageTag: d9eccb2d-2a55-4bd0-a94a-e40288f536f7

	measure 'Rank retailer (CT)' =
			
			If(NOT(ISBLANK([TTL weekly Sales TY ( Coppertone)])), calculate(RANKX(ALL('Retailer Image'[Retailers],'Retailer Image'[ÙRL link]),'Key Measures'[TTL weekly Sales TY ( Coppertone)])))
		formatString: 0
		lineageTag: ac0ae7cd-35ae-4dc5-a490-4b154ba772a6

	column Retailers
		dataType: string
		lineageTag: 1bcf3ad8-ca6b-41f3-8684-a946491d68aa
		summarizeBy: none
		sourceColumn: Retailers

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: 68f600b7-65f9-4a50-8180-03e2cdc798c0
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column 'ÙRL link'
		dataType: string
		lineageTag: fc932ec8-e27b-4141-90c2-adf83013c113
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: ÙRL link

		annotation SummarizationSetBy = Automatic

	partition 'Retailer Image-73bf3623-75fd-45e7-bbcf-d897ca6602bd' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVZtb6O4Fv4rq0r9NEviF8B4JDQihDRpm2mG5qXp7CgyYAgNAQokNP31a5M0Q7t3", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Retailers = _t, Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Retailers", type text}, {"Column1", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column2", "ÙRL link"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Retailers] <> "Rite Aid" and [Retailers] <> "Test" and [Retailers] <> "Test2"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

