table 'Week Table'
	lineageTag: e5c10ee8-80d3-4554-b759-49208f5dad54

	column Weeks
		dataType: int64
		formatString: 0
		lineageTag: 77af432f-3d55-4355-8fde-0b44501b1c74
		summarizeBy: sum
		sourceColumn: Weeks

		annotation SummarizationSetBy = Automatic

	column sort
		dataType: int64
		formatString: 0
		lineageTag: 4f923cbb-2271-43b4-8c0a-4de46724f12f
		summarizeBy: none
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

	column 'Last N Weeks'
		dataType: string
		lineageTag: 5174bbee-221e-48c4-8fe7-d213c70830f1
		summarizeBy: none
		sourceColumn: Last N Weeks
		sortByColumn: sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Week Table-5738fd15-eade-43a2-a39c-2834913eefe0' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSAWOfxOISBUOF8NTU7GKlWJ1oJROgoBFMwgRJwtAYKGoM12KMJGVkBhQ2gUkpGJkhyZmCDDODyZkaIUlZAgFQwhyII0NclGJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Weeks = _t, sort = _t, #"Last N Weeks" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Weeks", Int64.Type}, {"sort", Int64.Type}, {"Last N Weeks", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

